services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:3.1.2.1076-1-ls260@sha256:41c0507945fe572aa6e3711637a79dfc35d13acaf1bf5929714e9d157bd32e0d
    container_name: resilio-sync
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/resilio-sync/config:/config
      - ../../cloud-data/resilio-sync/data:/sync
    labels:
      - traefik.enable=true
      - traefik.http.services.resilio.loadbalancer.server.port=8888

      # HTTPS
      - traefik.http.routers.resilio.rule=Host(`resilio.${CLOUD_DOMAIN}`)
      - traefik.http.routers.resilio.tls.certresolver=mytlschallenge
      - traefik.http.routers.resilio.entrypoints=web-secured
      - traefik.http.routers.resilio.tls=true
      - traefik.http.routers.resilio.service=resilio

networks:
  web:
    external: true
