services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:3.1.2.1076-1-ls262@sha256:04c1b89e139c9486c0311c573cb6db2e386ba7fe19c0e22df1c2e77c37667da3
    container_name: resilio-sync
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/resilio-sync/config:/config
      - ../../cloud-data/resilio-sync/data:/sync
    labels:
      - traefik.enable=true
      - traefik.http.services.resilio.loadbalancer.server.port=8888

      # HTTPS
      - traefik.http.routers.resilio.rule=Host(`resilio.${CLOUD_DOMAIN}`)
      - traefik.http.routers.resilio.tls.certresolver=mytlschallenge
      - traefik.http.routers.resilio.entrypoints=web-secured
      - traefik.http.routers.resilio.tls=true
      - traefik.http.routers.resilio.service=resilio

networks:
  web:
    external: true
