version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.4
    restart: always
    environment:
      - MYSQL_LOG_CONSOLE=true
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - backend

  memcached:
    image: memcached:1.5.6
    restart: always
    entrypoint: memcached -m 256
    networks:
      - backend

  app:
    image: seafileltd/seafile-mc:7.1.4
    restart: always
    volumes:
      - data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=mariadb
      - TIME_ZONE=Etc/UTC  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=seafile.noizwaves.cloud # Specifies your host name if https is enabled.
    env_file:
      - .env
    depends_on:
      - mariadb
      - memcached
    networks:
      - web
      - backend
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.seafile.loadbalancer.server.port=80
      - traefik.http.services.seafile.loadbalancer.passhostheader=true

      ## HTTPS routing
      - traefik.http.routers.seafile-secure.rule=Host(`seafile.noizwaves.cloud`)
      - traefik.http.routers.seafile-secure.entrypoints=web-secured
      - traefik.http.routers.seafile-secure.service=seafile
      - traefik.http.routers.seafile-secure.tls=true
      - traefik.http.routers.seafile-secure.tls.certresolver=mytlschallenge

      ## HTTP traffic
      - traefik.http.routers.seafile.rule=Host(`seafile.noizwaves.cloud`)
      - traefik.http.routers.seafile.entrypoints=web
      - traefik.http.routers.seafile.middlewares=redirect@file

volumes:
  data:
    driver: local

  mariadb:
    driver: local

networks:
  backend:
    external: false
    internal: true

  web:
    external: true
