version: '3.7'

services:
  registry:
    image: registry:2
    restart: unless-stopped
    container_name: registry
    user: "1000:1000"
    volumes:
      - ../../cloud-data/registry/data:/var/lib/registry
    networks:
      - web
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.registry.loadbalancer.server.port=5000
      - traefik.http.services.registry.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.registry.rule=Host(`registry.${CLOUD_DOMAIN}`)
      - traefik.http.routers.registry.entrypoints=web-secured
      - traefik.http.routers.registry.service=registry
      - traefik.http.routers.registry.tls=true
      - traefik.http.routers.registry.tls.certresolver=mytlschallenge

networks:
  web:
    external: true
