version: '3.7'

services:
  mariadb:
    image: linuxserver/mariadb:110.4.13mariabionic-ls73
    container_name: standardnotes_mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=standard_notes
      - MYSQL_USER=standard_notes
    volumes:
      - ../../cloud-data/standardnotes/mariadb:/config
    networks:
      - backend

  sync:
    image: standardnotes/syncing-server:stable
    container_name: standardnotes_sync
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - EXPOSED_PORT=3000
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=standard_notes
      - DB_USERNAME=standard_notes
      - DISABLE_USER_REGISTRATION=false
    depends_on:
      - mariadb
    networks:
      - web
      - backend
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.notes-sync.loadbalancer.server.port=3000
      - traefik.http.services.notes-sync.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.notes-sync.rule=Host(`notes-sync.${CLOUD_DOMAIN}`)
      - traefik.http.routers.notes-sync.entrypoints=web-secured
      - traefik.http.routers.notes-sync.service=notes-sync
      - traefik.http.routers.notes-sync.tls=true
      - traefik.http.routers.notes-sync.tls.certresolver=mytlschallenge

  web:
    image: standardnotes/web:stable
    container_name: standardnotes_web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - EXPOSED_PORT=3000
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - APP_HOST=https://notes.${CLOUD_DOMAIN}
      - SF_DEFAULT_SERVER=https://notes-sync.${CLOUD_DOMAIN}
    networks:
      - web
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.notes-web.loadbalancer.server.port=3000
      - traefik.http.services.notes-web.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.notes-web.rule=Host(`notes.${CLOUD_DOMAIN}`)
      - traefik.http.routers.notes-web.entrypoints=web-secured
      - traefik.http.routers.notes-web.service=notes-web
      - traefik.http.routers.notes-web.tls=true
      - traefik.http.routers.notes-web.tls.certresolver=mytlschallenge

  extensions:
    build:
      context: ./extensions/
      dockerfile: Dockerfile
    container_name: standardnotes_extensions
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.notes-extensions.loadbalancer.server.port=80
      - traefik.http.services.notes-extensions.loadbalancer.passhostheader=true

      ## HTTPS
      - "traefik.http.routers.notes-extensions.rule=Host(`notes.${CLOUD_DOMAIN}`) && PathPrefix(`/extensions/`)"
      - traefik.http.routers.notes-extensions.entrypoints=web-secured
      - traefik.http.routers.notes-extensions.service=notes-extensions
      - traefik.http.routers.notes-extensions.tls=true
      - traefik.http.routers.notes-extensions.tls.certresolver=mytlschallenge

      - com.centurylinklabs.watchtower.enable=false

networks:
  backend:
    external: false
    internal: true

  web:
    external: true
