version: '3.7'

services:
  mariadb:
    image: linuxserver/mariadb:110.4.13mariabionic-ls73
    container_name: standardnotes_mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=standard_notes
      - MYSQL_USER=standard_notes
    volumes:
      - mariadb:/config
    networks:
      - backend

  sync:
    image: standardnotes/syncing-server:stable
    container_name: standardnotes_sync
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - EXPOSED_PORT=3000
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=standard_notes
      - DB_USERNAME=standard_notes
      - DISABLE_USER_REGISTRATION=false
    depends_on:
      - mariadb
    networks:
      - web
      - backend
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.notes-sync.loadbalancer.server.port=3000
      - traefik.http.services.notes-sync.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.notes-sync.rule=Host(`notes-sync.noizwaves.cloud`)
      - traefik.http.routers.notes-sync.entrypoints=web-secured
      - traefik.http.routers.notes-sync.service=notes-sync
      - traefik.http.routers.notes-sync.tls=true
      - traefik.http.routers.notes-sync.tls.certresolver=mytlschallenge

  web:
    image: standardnotes/web:stable
    container_name: standardnotes_web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - EXPOSED_PORT=3000
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - APP_HOST=https://notes.noizwaves.cloud
      - SF_DEFAULT_SERVER=https://notes-sync.noizwaves.cloud
    networks:
      - web
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.notes-web.loadbalancer.server.port=3000
      - traefik.http.services.notes-web.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.notes-web.rule=Host(`notes.noizwaves.cloud`)
      - traefik.http.routers.notes-web.entrypoints=web-secured
      - traefik.http.routers.notes-web.service=notes-web
      - traefik.http.routers.notes-web.tls=true
      - traefik.http.routers.notes-web.tls.certresolver=mytlschallenge

  markdown-pro:
    build:
      context: ./markdown-pro/
      dockerfile: Dockerfile
      args:
        - VERSION=1.3.8
    container_name: standardnotes_markdown_pro
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.notes-markdown-pro.loadbalancer.server.port=80
      - traefik.http.services.notes-markdown-pro.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.notes-markdown-pro.rule=Host(`notes-markdown-pro.noizwaves.cloud`)
      - traefik.http.routers.notes-markdown-pro.entrypoints=web-secured
      - traefik.http.routers.notes-markdown-pro.service=notes-markdown-pro
      - traefik.http.routers.notes-markdown-pro.tls=true
      - traefik.http.routers.notes-markdown-pro.tls.certresolver=mytlschallenge

  folders:
    build:
      context: ./folders/
      dockerfile: Dockerfile
      args:
        - VERSION=1.3.3
    container_name: standardnotes_folders
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.notes-folders.loadbalancer.server.port=80
      - traefik.http.services.notes-folders.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.notes-folders.rule=Host(`notes-folders.noizwaves.cloud`)
      - traefik.http.routers.notes-folders.entrypoints=web-secured
      - traefik.http.routers.notes-folders.service=notes-folders
      - traefik.http.routers.notes-folders.tls=true
      - traefik.http.routers.notes-folders.tls.certresolver=mytlschallenge


volumes:
  mariadb:
    driver: local

networks:
  backend:
    external: false
    internal: true

  web:
    external: true
