version: '3.7'

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    user: "1000:1000"
    restart: always
    networks:
      - web
    volumes:
      - ../../cloud-data/bitwarden/data:/data
    environment:
      ROCKET_PORT: "10000"
      DOMAIN: "https://bitwarden.${CLOUD_DOMAIN}"
      LOG_FILE: '/data/bitwarden.log'
      SIGNUPS_ALLOWED: 'true'
      WEBSOCKET_ENABLED: 'true'
    env_file:
      - .env
    labels:
      - traefik.enable=true

      - traefik.http.services.bitwarden.loadbalancer.passhostheader=true
      - traefik.http.services.bitwarden.loadbalancer.server.port=10000

      - traefik.http.services.bitwarden-websocket.loadbalancer.passhostheader=true
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012

      - traefik.http.routers.bitwarden.rule=Host(`bitwarden.${CLOUD_DOMAIN}`)
      - traefik.http.routers.bitwarden.service=bitwarden
      - traefik.http.routers.bitwarden.entrypoints=web-secured
      - traefik.http.routers.bitwarden.tls=true
      - traefik.http.routers.bitwarden.tls.certresolver=mytlschallenge

      - traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.${CLOUD_DOMAIN}`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket
      - traefik.http.routers.bitwarden-websocket.entrypoints=web-secured
      - traefik.http.routers.bitwarden-websocket.tls=true
      - traefik.http.routers.bitwarden-websocket.tls.certresolver=mytlschallenge

      ## DNS
      - external-dns-poc=bitwarden.${CLOUD_DOMAIN}

networks:
  web:
    external: true