version: '3.7'

services:
  server:
    container_name: k3s_server
    hostname: k3s
    image: "rancher/k3s:latest"
    command: server
    tmpfs:
      - /run
      - /var/run
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: unless-stopped
    environment:
      K3S_KUBECONFIG_OUTPUT: /kubeconfig/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: '666'
      # TODO: chown?
    env_file:
      - .env
    volumes:
      - ../../cloud-data/k3s/server:/var/lib/rancher/k3s
      - ../../cloud-data/k3s/kubeconfig:/kubeconfig
    ports: [] # expose no ports, use tailscale instead

  tailscale:
    container_name: k3s_tailscale
    image: tailscale/tailscale:latest
    network_mode: service:server
    cap_add:
      - NET_ADMIN
    environment:
      TS_EXTRA_ARGS: "--hostname=k3s"
      TS_STATE_DIR: /var/lib/tailscale/
    volumes:
      - ../../cloud-data/k3s/tailscale:/var/lib/tailscale
