version: '3.7'

services:
  server:
    container_name: k3s_server
    hostname: k3s
    image: "rancher/k3s:latest"
    command: server
    tmpfs:
      - /run
      - /var/run
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: unless-stopped
    environment:
      K3S_KUBECONFIG_OUTPUT: /kubeconfig/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: '666'
      # TODO: chown?
    env_file:
      - .env
    volumes:
      - ../../cloud-data/k3s/server:/var/lib/rancher/k3s
      - ../../cloud-data/k3s/kubeconfig:/kubeconfig
      # Customize Traefik ingress configuration
      # - ./traefik-config.yaml:/var/lib/rancher/k3s/server/manifests/traefik-config.yaml:ro
    ports:
      - 6443:6443
      - 8443:443
      - 8080:80
