version: '3.7'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex.noizwaves.cloud
    restart: unless-stopped
    network_mode: host
    environment:
      - VERSION=docker
      - TZ=America/Denver
      - ADVERTISE_IP=https://plex.${CLOUD_DOMAIN}:32400
      - PLEX_UID=${USER}
      - PLEX_GID=${USER}
#      - PLEX_CLAIM=claim-xxxxxxxxxxxxxx
    volumes:
      - ../../cloud-data/plex/config:/config
      - ../../cloud-data/plex/data:/data
      - ../../cloud-data/resilio-sync/data/encrypted-data/Videos/Tony Riddle:/data-other/misc/tony:ro
      - ../../cloud-data/plex/transcode:/transcode
    devices:
      - /dev/dri:/dev/dri
