version: '3.7'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex.${CLOUD_DOMAIN}
    restart: unless-stopped
    environment:
      - VERSION=docker
      - TZ=${TZ}
      - ADVERTISE_IP=https://plex.${CLOUD_DOMAIN}
      - PLEX_UID=${USER}
      - PLEX_GID=${USER}
#      - PLEX_CLAIM=claim-xxxxxxxxxxxxxx
    networks:
      - default
      - web
    volumes:
      - ../../cloud-data/plex/config:/config
      - ../../cloud-data/plex/transcode:/transcode
      - /mnt/media2:/data-media2:ro
      - ../../cloud-data/resilio-sync/data/encrypted-data/Videos/Tony Riddle:/data-other/misc/tony:ro
      - ../../cloud-data/resilio-sync/data/pictures-data/iCloud_Photos:/data-other/photos/iCloud_Photos:ro
      - ../../cloud-data/resilio-sync/data/doc-sync-data/music:/data-other/music/doc-sync:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.plex.loadbalancer.server.port=32400

      # HTTPS
      - traefik.http.routers.plex.rule=Host(`plex.${CLOUD_DOMAIN}`)
      - traefik.http.routers.plex.tls.certresolver=mytlschallenge
      - traefik.http.routers.plex.entrypoints=web-secured
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.service=plex
    devices:
      - /dev/dri:/dev/dri

  tailscale:
    image: tailscale/tailscale
    container_name: plex_tailscale
    hostname: plex
    restart: unless-stopped
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - ../../cloud-data/plex/tailscale:/var/lib/tailscale
      - ./serve-config.json:/config/serve-config.json
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_OAUTH_KEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --reset
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_USERSPACE=false
    labels:
      # Automatically updated
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true
