version: '3.7'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex.${CLOUD_DOMAIN}
    restart: unless-stopped
    environment:
      - VERSION=docker
      - TZ=America/Denver
      - ADVERTISE_IP=http://plex.${CLOUD_DOMAIN}:32400,http://${TAILSCALE_IP}:32400,http://${LAN_IP}:32400
      - PLEX_UID=${USER}
      - PLEX_GID=${USER}
#      - PLEX_CLAIM=claim-xxxxxxxxxxxxxx
    network_mode: host
    volumes:
      - ../../cloud-data/plex/config:/config
      - ../../cloud-data/plex/transcode:/transcode
      - /mnt/media:/data-media:ro
      - /mnt/media2:/data-media2:ro
      - ../../cloud-data/resilio-sync/data/encrypted-data/Videos/Tony Riddle:/data-other/misc/tony:ro
      - ../../cloud-data/resilio-sync/data/pictures-data/iCloud_Photos:/data-other/photos/iCloud_Photos:ro
      - ../../cloud-data/resilio-sync/data/doc-sync-data/music:/data-other/music/doc-sync:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.plex.loadbalancer.server.port=32400

      # HTTPS
      - traefik.http.routers.plex.rule=Host(`plex.${CLOUD_DOMAIN}`)
      - traefik.http.routers.plex.tls.certresolver=mytlschallenge
      - traefik.http.routers.plex.entrypoints=web-secured
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.service=plex

      # HTTP redirect
      - traefik.http.middlewares.plex-redirect.redirectregex.regex=^https://plex.${CLOUD_DOMAIN}/(.*?)
      - traefik.http.middlewares.plex-redirect.redirectregex.replacement=https://plex.${CLOUD_DOMAIN}:32400/$${1}
      - traefik.http.routers.plex.middlewares=plex-redirect@docker

      ## DNS
      - external-dns-poc=plex.${CLOUD_DOMAIN}

    devices:
      - /dev/dri:/dev/dri
