version: '3.7'

services:
  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    volumes:
      - ./config:/config
    networks:
      - web
      - backend
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - jwt
      - session
      - mysql_password
    labels:
      - 'traefik.enable=true'
      - traefik.http.routers.authelia.rule=Host(`authelia.${CLOUD_DOMAIN}`)
      - 'traefik.http.routers.authelia.entrypoints=web-secured'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.certresolver=mytlschallenge'

      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.${CLOUD_DOMAIN}/"
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups'
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb

  redis:
    image: redis:6.0.5
    container_name: authelia_redis
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ../../cloud-data/authelia/redis:/data

  mariadb:
    image: mariadb:10.5.4
    container_name: authelia_mariadb
    restart: unless-stopped
    networks:
      - backend
    secrets:
      - mysql_password
    environment:
      - MYSQL_USER=authelia
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=authelia
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ../../cloud-data/authelia/mariadb:/var/lib/mysql

volumes:
  redis:
    driver: local

  mariadb:
    driver: local

secrets:
  jwt:
    file: .secrets/jwt.txt

  session:
    file: .secrets/session.txt

  mysql_password:
    file: .secrets/mysql_password.txt

networks:
  web:
    external: true

  backend:
    external: false
    internal: true
