version: '3.7'
services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy
    restart: unless-stopped
    command:
      - serve
    user: 1000:1000
    networks:
      - web
      - ntfy
    volumes:
      - ./server.yml:/etc/ntfy/server.yml
      - ../../cloud-data/ntfy:/var/cache/ntfy
    environment:
      - TZ=${TZ}
    # healthcheck:
    #     test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
    #     interval: 60s
    #     timeout: 10s
    #     retries: 3
    #     start_period: 40s
    labels:
      - traefik.enable=true

      - traefik.http.services.ntfy.loadbalancer.passhostheader=true
      - traefik.http.services.ntfy.loadbalancer.server.port=80

      - traefik.http.routers.ntfy.rule=Host(`ntfy.${CLOUD_DOMAIN}`)
      - traefik.http.routers.ntfy.service=ntfy
      - traefik.http.routers.ntfy.entrypoints=web-secured
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.routers.ntfy.tls.certresolver=mytlschallenge

      # Automatically updated
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true
  ntfy:
    external: false
    internal: true
    name: ntfy
