version: '3.7'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - "${TAILSCALE_IP}:53:53/tcp"
      - "${TAILSCALE_IP}:53:53/udp"
    networks:
      - web
    environment:
      - TZ=America/Denver
      - DNS1=9.9.9.9
      - DNS2=1.1.1.1
      - VIRTUAL_HOST=pihole.${NODE_NAME}.${CLOUD_DOMAIN}
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    volumes:
      - ../../cloud-data/pihole/config:/etc/pihole
      - ../../cloud-data/pihole/dnsmasq:/etc/dnsmasq.d
    dns:
      - 1.1.1.1
      - 9.9.9.9
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole-web.loadbalancer.server.port=80

      # HTTPS
      - traefik.http.routers.pihole-web.rule=Host(`pihole.${NODE_NAME}.${CLOUD_DOMAIN}`)
      - traefik.http.routers.pihole-web.tls.certresolver=mytlschallenge
      - traefik.http.routers.pihole-web.entrypoints=web-secured
      - traefik.http.routers.pihole-web.tls=true
      - traefik.http.routers.pihole-web.service=pihole-web

      # Automatically updated
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true
