version: '3.7'

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:5.1.2-ls269@sha256:d22bc8b3185f0e0c1050f6427df6b9ad072f70586b3b1edf916131b0c3101542
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/sabnzbd/config:/config
      - /merged/media/Arr:/data
    ports: []
    labels:
      - traefik.enable=true
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080

      # HTTPS
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${CLOUD_DOMAIN}`)
      - traefik.http.routers.sabnzbd.tls.certresolver=mytlschallenge
      - traefik.http.routers.sabnzbd.entrypoints=web-secured
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.routers.sabnzbd.service=sabnzbd

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.19.2979-ls322@sha256:c19aa4ecdf03d73e1d5c901da33744cb7eb4d921f89bafed1ca264601d7fa224
    container_name: sonarr
    restart: unless-stopped
    networks:
      - web
      - ntfy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/sonarr/config:/config
      - /merged/media/Arr:/data
    ports: []
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

      # HTTPS
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${CLOUD_DOMAIN}`)
      - traefik.http.routers.sonarr.tls.certresolver=mytlschallenge
      - traefik.http.routers.sonarr.entrypoints=web-secured
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.service=sonarr

  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0.10514-ls314@sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438
    container_name: radarr
    restart: unless-stopped
    networks:
      - web
      - ntfy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/radarr/config:/config
      - /merged/media/Arr:/data
    ports: []
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878

      # HTTPS
      - traefik.http.routers.radarr.rule=Host(`radarr.${CLOUD_DOMAIN}`)
      - traefik.http.routers.radarr.tls.certresolver=mytlschallenge
      - traefik.http.routers.radarr.entrypoints=web-secured
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.service=radarr

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls40@sha256:c74c32408fdf6e7926ad62641fc1a5544206ee65c33f2188bb179edb30e28f5a
    container_name: lidarr
    restart: unless-stopped
    networks:
      - web
      - ntfy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/lidarr/config:/config
      - /merged/media/Arr:/data
    ports: []
    labels:
      - traefik.enable=true
      - traefik.http.services.lidarr.loadbalancer.server.port=8686

      # HTTPS
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${CLOUD_DOMAIN}`)
      - traefik.http.routers.lidarr.tls.certresolver=mytlschallenge
      - traefik.http.routers.lidarr.entrypoints=web-secured
      - traefik.http.routers.lidarr.tls=true
      - traefik.http.routers.lidarr.service=lidarr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.5.2.5491-ls157@sha256:ab91301778251f82a31bbfc87f0497376d59e84439d9a1ceff6a61d594d1e3d7
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/prowlarr/config:/config
    ports: []
    labels:
      - traefik.enable=true
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

      # HTTPS
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${CLOUD_DOMAIN}`)
      - traefik.http.routers.prowlarr.tls.certresolver=mytlschallenge
      - traefik.http.routers.prowlarr.entrypoints=web-secured
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.service=prowlarr

networks:
  web:
    external: true
  ntfy:
    external: true
