version: '3.7'

services:
  speedtest:
    image: adolfintel/speedtest
    hostname: speedtest.${CLOUD_DOMAIN}
    container_name: speedtest
    restart: unless-stopped
    environment: {}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.services.speedtest.loadbalancer.server.port=80

      # HTTPS
      - traefik.http.routers.speedtest.rule=Host(`speedtest.${CLOUD_DOMAIN}`)
      - traefik.http.routers.speedtest.tls.certresolver=mytlschallenge
      - traefik.http.routers.speedtest.entrypoints=web-secured
      - traefik.http.routers.speedtest.tls=true
      - traefik.http.routers.speedtest.service=speedtest

      ## DNS
      - external-dns-poc=speedtest.${CLOUD_DOMAIN}

networks:
  web:
    external: true
