services:
  speedtest:
    image: ghcr.io/librespeed/speedtest:6.2.1@sha256:705744f487048f209b4e389312ea82d4d5c36a76db3e5123b97d4b1649b724b5
    container_name: speedtest
    hostname: speedtest.${CLOUD_DOMAIN}
    restart: unless-stopped
    networks:
      - web
    ports:
      - "8080:8080"
    environment:
      - USE_NEW_DESIGN=true
    labels:
      - traefik.enable=true
      - traefik.http.services.speedtest.loadbalancer.server.port=8080

      # HTTPS
      - traefik.http.routers.speedtest.rule=Host(`speedtest.${CLOUD_DOMAIN}`)
      - traefik.http.routers.speedtest.tls.certresolver=mytlschallenge
      - traefik.http.routers.speedtest.entrypoints=web-secured
      - traefik.http.routers.speedtest.tls=true
      - traefik.http.routers.speedtest.service=speedtest

      # HTTP redirect
      - traefik.http.middlewares.speedtest-redirect.redirectregex.regex=^https://speedtest.${CLOUD_DOMAIN}/(.*)
      - traefik.http.middlewares.speedtest-redirect.redirectregex.replacement=http://speedtest.${CLOUD_DOMAIN}:8080/$${1}
      - traefik.http.routers.speedtest.middlewares=speedtest-redirect@docker

networks:
  web:
    external: true
