version: '3.7'

services:
  fotos:
    image: ghcr.io/noizwaves/fotos:latest
    container_name: fotos
    hostname: fotos
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - backend
    environment:
      - TZ=America/Denver
      - PORT=3000
    volumes:
      - ../../cloud-data/fotos/thumbnails/v2:/thumbnails_v2
      - ../../cloud-data/fotos/normals:/normals
      - ../../cloud-data/resilio-sync/data/pictures-data/iCloud_Photos:/originals:ro
      - ../../cloud-data/resilio-sync/data/pictures-data/iCloud_Albums:/albums

  nginx:
    image: nginx:1.19.1
    container_name: fotos_nginx
    hostname: fotos_nginx
    restart: unless-stopped
    depends_on:
      - fotos
    networks:
      - web
      - backend
    environment:
      - TZ=America/Denver
    volumes:
      - ../../cloud-data/fotos/thumbnails/v2:/usr/share/nginx/html/thumbnails_v2:ro
      - ../../cloud-data/resilio-sync/data/pictures-data/iCloud_Photos:/usr/share/nginx/html/photos:ro
      - ./fotos.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.fotos-nginx.loadbalancer.server.port=80

      # HTTPS
      - traefik.http.routers.fotos-nginx.rule=Host(`fotos.${CLOUD_DOMAIN}`)
      - traefik.http.routers.fotos-nginx.tls.certresolver=mytlschallenge
      - traefik.http.routers.fotos-nginx.entrypoints=web-secured
      - traefik.http.routers.fotos-nginx.tls=true
      - traefik.http.routers.fotos-nginx.service=fotos-nginx

      # protect with Authelia
      - traefik.http.routers.fotos-nginx.middlewares=authelia@docker

      ## DNS
      - external-dns-poc=fotos.${CLOUD_DOMAIN}

  webdav:
    image: linuxserver/nginx:latest
    container_name: fotos_webdav
    hostname: fotos_webdav
    restart: unless-stopped
    networks:
      - web
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - ./webdav.conf:/config/nginx/site-confs/default.conf
      - ./credentials.list:/etc/nginx/.credentials.list
      - ../../cloud-data/resilio-sync/data/pictures-data/iCloud_Photos:/webdav
    labels:
      - traefik.enable=true
      - traefik.http.services.fotos-webdav.loadbalancer.server.port=80

      # HTTPS
      - "traefik.http.routers.fotos-webdav.rule=Host(`fotos.${CLOUD_DOMAIN}`) && PathPrefix(`/webdav/`)"
      - traefik.http.routers.fotos-webdav.tls.certresolver=mytlschallenge
      - traefik.http.routers.fotos-webdav.entrypoints=web-secured
      - traefik.http.routers.fotos-webdav.middlewares=fotos-webdav-prefix
      - traefik.http.routers.fotos-webdav.tls=true
      - traefik.http.routers.fotos-webdav.service=fotos-webdav

      - traefik.http.middlewares.fotos-webdav-prefix.stripprefix.prefixes=/webdav

networks:
  backend:

  web:
    external: true
