# Inspired from https://medium.com/faun/deploy-nextcloud-with-docker-compose-traefik-2-postgresql-and-redis-fd1ffc166173

version: '3.3'

volumes:
  nextcloud-www:
    driver: local
  nextcloud-db:
    driver: local
  redis:
    driver: local

services:
  db:
    restart: always
    image: mariadb:10.5.4
    networks:
      - backend
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
  redis:
    image: redis:6.0.5
    restart: always
    networks:
      - backend
    volumes:
      - redis:/var/lib/redis

  nextcloud:
    image: nextcloud:19.0.0
    restart: always
    networks:
      - web
      - backend
    depends_on:
      - redis
      - db
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.noizwaves.cloud`)"
      - "traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.service=nextcloud"

      ## - "traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect"

      ## - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://mydomain.com"
      ## - "traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' mydomain.com *.mydomain.net"
      ## - "traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011"
      ## - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
      ## - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"

      ## - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav"
      ## - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/"
    environment:
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD

      # As we are running behind a proxy... from `$ docker network inspect web`
      - TRUSTED_PROXIES=172.20.0.0/16
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.noizwaves.cloud
    volumes:
      - nextcloud-www:/var/www/html

networks:
  backend:
    external: false
  web:
    external: true