# Inspired from https://medium.com/faun/deploy-nextcloud-with-docker-compose-traefik-2-postgresql-and-redis-fd1ffc166173

version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.4
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:6.0.5
    restart: always
    networks:
      - backend
    volumes:
      - redis:/data

  app:
    image: nextcloud:19.0.0
    restart: always
    networks:
      - web
      - backend
    depends_on:
      - redis
      - mariadb
    labels:
      - traefik.enable=true

      - traefik.http.services.nextcloud.loadbalancer.server.port=80

      # HTTPS
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.noizwaves.cloud`)
      - traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge
      - traefik.http.routers.nextcloud.entrypoints=web-secured
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.service=nextcloud

      # Authelia protection disabled
      ## - traefik.http.routers.nextcloud.middlewares=authelia@docker

      ## - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect

      ## - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://mydomain.com
      ## - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' mydomain.com *.mydomain.net
      ## - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      ## - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      ## - traefik.http.middlewares.nextcloud.headers.stsPreload=true

      ## - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
      ## - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis

      # As we are running behind a proxy... from `$ docker network inspect web`
      - TRUSTED_PROXIES=172.20.0.0/16
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.noizwaves.cloud
    env_file:
      - .env
    volumes:
      - data:/var/www/html

volumes:
  data:
    driver: local

  mariadb:
    driver: local

  redis:
    driver: local

networks:
  backend:
    external: false
    internal: true

  web:
    external: true