# Inspired from https://medium.com/faun/deploy-nextcloud-with-docker-compose-traefik-2-postgresql-and-redis-fd1ffc166173

version: '3.7'

services:
  mariadb:
    image: linuxserver/mariadb:11.4.5-r0-ls185
    container_name: nextcloud_mariadb
    restart: always
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=nextcloud
    env_file:
      - .env
    volumes:
      - ../../cloud-data/nextcloud/mariadb:/config

  app:
    image: linuxserver/nextcloud:19.0.1-ls91
    container_name: nextcloud
    restart: always
    networks:
      - web
      - backend
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true

      # Use Nextcloud's self signed SSL
      - traefik.http.services.nextcloud.loadbalancer.server.port=443
      - traefik.http.services.nextcloud.loadbalancer.server.scheme=https

      # HTTPS
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${CLOUD_DOMAIN}`)
      - traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge
      - traefik.http.routers.nextcloud.entrypoints=web-secured
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.service=nextcloud
      - traefik.http.routers.nextcloud.middlewares=nextcloud_hsts

      # HSTS
      - traefik.http.middlewares.nextcloud_hsts.headers.stsSeconds=15552000
      - traefik.http.middlewares.nextcloud_hsts.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud_hsts.headers.stsIncludeSubdomains=true

      # Authelia protection disabled
      ## - traefik.http.routers.nextcloud.middlewares=authelia@docker
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ../../cloud-data/nextcloud/data:/data
      - ../../cloud-data/nextcloud/config:/config

networks:
  backend:
    external: false
    internal: true

  web:
    external: true
