# Inspired from https://medium.com/faun/deploy-nextcloud-with-docker-compose-traefik-2-postgresql-and-redis-fd1ffc166173

version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.4
    container_name: nextcloud_mariadb
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  app:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - web
      - backend
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true

      # Use Nextcloud's self signed SSL
      - traefik.http.services.nextcloud.loadbalancer.server.port=443
      - traefik.http.services.nextcloud.loadbalancer.server.scheme=https

      # HTTPS
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.noizwaves.cloud`)
      - traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge
      - traefik.http.routers.nextcloud.entrypoints=web-secured
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.service=nextcloud
      - traefik.http.routers.nextcloud.middlewares=nextcloud_hsts

      # HSTS
      - traefik.http.middlewares.nextcloud_hsts.headers.stsSeconds=15552000
      - traefik.http.middlewares.nextcloud_hsts.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud_hsts.headers.stsIncludeSubdomains=true

      # Authelia protection disabled
      ## - traefik.http.routers.nextcloud.middlewares=authelia@docker
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - data:/data
      - config:/config

volumes:
  data:
    driver: local

  config:
    driver: local

  mariadb:
    driver: local

networks:
  backend:
    external: false
    internal: true

  web:
    external: true