version: '3.7'

services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    restart: unless-stopped
    container_name: watchtower
    env_file:
      - .env
    environment:
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_SCHEDULE=0 0 2 ? * SAT
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_TIMEOUT=60s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
