version: '3.7'

services:
  app:
    container_name: atuin
    image: ghcr.io/atuinsh/atuin:v18.3.0
    restart: unless-stopped
    command: server start
    networks:
      - web
      - backend
    volumes:
      - "../../cloud-data/atuin/config:/config"
    links:
      - db
    ports: []
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
    labels:
      - traefik.enable=true

      - traefik.http.services.atuin.loadbalancer.passhostheader=true
      - traefik.http.services.atuin.loadbalancer.server.port=8888

      - traefik.http.routers.atuin.rule=Host(`atuin.${CLOUD_DOMAIN}`)
      - traefik.http.routers.atuin.service=atuin
      - traefik.http.routers.atuin.entrypoints=web-secured
      - traefik.http.routers.atuin.tls=true
      - traefik.http.routers.atuin.tls.certresolver=mytlschallenge
  db:
    container_name: atuin_postgres
    image: postgres:15-alpine
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - backend
    volumes:
      - "../../cloud-data/atuin/postgres:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}

networks:
  web:
    external: true
  backend:
    external: false
    internal: true
