version: "3.7"
services:
  app:
    image: adguard/adguardhome:latest
    hostname: adguard
    container_name: adguard
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../../cloud-data/adguard/work:/opt/adguardhome/work
      - ../../cloud-data/adguard/conf:/opt/adguardhome/conf

networks:
  web:
    external: true
