version: "3.7"
services:
  app:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    user: "1000:1000"
    restart: unless-stopped
    network_mode: service:tailscale
    depends_on:
      - "tailscale"
    volumes:
      - ../../cloud-data/adguard/work:/opt/adguardhome/work
      - ../../cloud-data/adguard/conf:/opt/adguardhome/conf

  tailscale:
    hostname: dns
    container_name: adguardhome_tailscale
    restart: unless-stopped
    build:
      context: https://github.com/tailscale/tailscale.git#v1.14.4
      args:
        VERSION_LONG: "1.14.4"
        VERSION_SHORT: "1.14.4"
        VERSION_GIT_HASH: "3a72ebb109433969b060e1b2c9142dee53fc4756"
    command: tailscaled
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - ../../cloud-data/adguard/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    labels:
      - com.centurylinklabs.watchtower.enable=false
