version: "3.7"
services:
  app:
    image: adguard/adguardhome:latest
    hostname: adguard
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - web
    volumes:
      - ../../cloud-data/adguard/work:/opt/adguardhome/work
      - ../../cloud-data/adguard/conf:/opt/adguardhome/conf
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.adguard.loadbalancer.server.port=3000

      ## HTTPS
      - traefik.http.routers.adguard.rule=Host(`adguard.${NODE_NAME}.${CLOUD_DOMAIN}`)
      - traefik.http.routers.adguard.entrypoints=web-secured
      - traefik.http.routers.adguard.service=adguard
      - traefik.http.routers.adguard.tls=true
      - traefik.http.routers.adguard.tls.certresolver=mytlschallenge

networks:
  web:
    external: true
