image:
  tag: "v1.103.1"

immich:
  persistence:
    library:
      existingClaim: immich

server:
  ingress:
    main:
      enabled: true
      hosts:
        - host: immich2
          paths:
            - path: "/"
              service:
                name: immich-server
                port: "3001"

      ingressClassName: tailscale
      tls:
      - hosts:
        - immich2
  persistence:
    # https://bjw-s.github.io/helm-charts/docs/common-library/storage/types/hostPath/
    adams-photos:
      enabled: true
      mountPath: /external/adam
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/iCloud_Photos
      readOnly: true
    laurens-photos:
      enabled: true
      mountPath: /external/lauren
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/Lauren Photos
      readOnly: true


microservices:
  persistence:
    adams-photos:
      enabled: true
      mountPath: /external/adam
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/iCloud_Photos
      readOnly: true
    laurens-photos:
      enabled: true
      mountPath: /external/lauren
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/Lauren Photos
      readOnly: true

postgresql:
  enabled: true

redis:
  enabled: true

machine-learning:
  enabled: false
