image:
  tag: "v1.103.1"

immich:
  persistence:
    library:
      existingClaim: immich

server:
  ingress:
    main:
      enabled: true
      hosts:
        - host: immich2
          paths:
            - path: "/"
              service:
                name: immich-server
                port: "3001"

      ingressClassName: tailscale
      tls:
      - hosts:
        - immich2

postgresql:
  enabled: true

redis:
  enabled: true

machine-learning:
  enabled: false
