image:
  tag: "v1.112.1"

immich:
  persistence:
    library:
      existingClaim: immich

server:
  ingress:
    main:
      enabled: true
      hosts:
        - host: immich2
          paths:
            - path: "/"
              service:
                name: immich-server
                port: "3001"
      ingressClassName: tailscale
      tls:
      - hosts:
        - immich2
    internal:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: immich.noizwaves.cloud
          paths:
            - path: "/"
              service:
                name: immich-server
                port: "3001"
      tls:
        - secretName: testsecret-tls
          hosts:
          - immich.noizwaves.cloud

  persistence:
    # https://bjw-s.github.io/helm-charts/docs/common-library/storage/types/hostPath/
    adams-photos:
      enabled: true
      mountPath: /external/adam
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/iCloud_Photos
      readOnly: true
    laurens-photos:
      enabled: true
      mountPath: /external/lauren
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/Lauren Photos
      readOnly: true
    photograph:
      enabled: true
      mountPath: /external/photography
      type: hostPath
      hostPath: /mnt/media2/Photography
      readOnly: true


microservices:
  persistence:
    adams-photos:
      enabled: true
      mountPath: /external/adam
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/iCloud_Photos
      readOnly: true
    laurens-photos:
      enabled: true
      mountPath: /external/lauren
      type: hostPath
      hostPath: /home/cloud/cloud-data/resilio-sync/data/pictures-data/Lauren Photos
      readOnly: true
    photograph:
      enabled: true
      mountPath: /external/photography
      type: hostPath
      hostPath: /mnt/media2/Photography
      readOnly: true

postgresql:
  enabled: true

redis:
  enabled: true

machine-learning:
  enabled: true
  persistence:
    cache:
      existingClaim: immich-cache
