version: '3.7'

services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:4
    container_name: upsnap
    network_mode: host
    restart: unless-stopped
    volumes:
      - ../../cloud-data/upsnap/data:/app/pb_data
    environment:
      - TZ=${TZ}
    labels:
      # Automatically updated
      - com.centurylinklabs.watchtower.enable=true

  proxy:
    container_name: upsnap-proxy
    image: alpine/socat
    networks:
      - web
    restart: unless-stopped
    command: "TCP-LISTEN:8080,fork,reuseaddr TCP:172.17.0.1:8090"
    depends_on:
      - upsnap
    ports: []
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.upsnap.loadbalancer.server.port=8080
      - traefik.http.services.upsnap.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.upsnap.rule=Host(`upsnap.${CLOUD_DOMAIN}`)
      - traefik.http.routers.upsnap.entrypoints=web-secured
      - traefik.http.routers.upsnap.service=upsnap
      - traefik.http.routers.upsnap.tls=true
      - traefik.http.routers.upsnap.tls.certresolver=mytlschallenge

      # Automatically updated
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true
