version: '3.7'

services:
  app:
    image: vikunja/vikunja:0.24.6
    container_name: vikunja
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - .env
    volumes:
      - ../../cloud-data/vikunja/files:/app/vikunja/files
    networks:
      - web
      - backend
    depends_on:
      - db
    restart: unless-stopped
    labels:
      - traefik.enable=true

      ## Service settings
      - traefik.http.services.vikunja.loadbalancer.server.port=3456
      - traefik.http.services.vikunja.loadbalancer.passhostheader=true

      ## HTTPS
      - traefik.http.routers.vikunja.rule=Host(`vikunja.${CLOUD_DOMAIN}`)
      - traefik.http.routers.vikunja.entrypoints=web-secured
      - traefik.http.routers.vikunja.service=vikunja
      - traefik.http.routers.vikunja.tls=true
      - traefik.http.routers.vikunja.tls.certresolver=mytlschallenge

  db:
    image: linuxserver/mariadb:11.4.5-r0-ls185
    container_name: vikunja_db
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ../../cloud-data/vikunja/mariadb:/config

networks:
  web:
    external: true

  backend:
    external: false
    internal: true
