version: '3.7'

services:
  bitwarden:
    image: bitwardenrs/server:1.15.1
    container_name: bitwarden_rs
    restart: always
    networks:
      - web
    volumes:
      - data:/data
    environment:
      DOMAIN: "https://bitwarden.${CLOUD_DOMAIN}"
      LOG_FILE: '/data/bitwarden.log'
      SIGNUPS_ALLOWED: 'false'
      WEBSOCKET_ENABLED: 'true'
    env_file:
      - .env
    labels:
      - traefik.enable=true

      - traefik.http.services.bitwarden.loadbalancer.passhostheader=true
      - traefik.http.services.bitwarden.loadbalancer.server.port=80

      - traefik.http.services.bitwarden-websocket.loadbalancer.passhostheader=true
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012

      - traefik.http.routers.bitwarden.rule=Host(`bitwarden.${CLOUD_DOMAIN}`)
      - traefik.http.routers.bitwarden.service=bitwarden
      - traefik.http.routers.bitwarden.entrypoints=web-secured
      - traefik.http.routers.bitwarden.tls=true
      - traefik.http.routers.bitwarden.tls.certresolver=mytlschallenge

      - traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.${CLOUD_DOMAIN}`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket
      - traefik.http.routers.bitwarden-websocket.entrypoints=web-secured
      - traefik.http.routers.bitwarden-websocket.tls=true
      - traefik.http.routers.bitwarden-websocket.tls.certresolver=mytlschallenge

volumes:
  data:
    driver: local

networks:
  web:
    external: true