version: '3.7'

services:
  cloudflare:
    image: cloudflare/cloudflared:2021.9.0
    restart: unless-stopped
    container_name: cloudflared
    command:
      - tunnel
      - run
      - traefik
    volumes:
      - ../../cloud-data/cloudflare/data:/home/nonroot/.cloudflared
    networks:
      # so cloudflared can connect to Traefik
      - public

networks:
  public:
    external: true
