version: '3.7'

services:
  app:
    container_name: docker-external-dns-poc
    build:
      dockerfile: Dockerfile
      context: ~/workspace/docker-external-dns-poc
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - .env
    labels:
      # No automatic updates
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
