services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.30.0-ls322@sha256:5358f396069b36f1399b16a4a368869ed8c1ccca16d15778bbc7782b76fba57e
    container_name: freshrss
    restart: unless-stopped
    networks:
      - web
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../../cloud-data/freshrss/config:/config
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80

      # HTTPS
      - traefik.http.routers.freshrss.rule=Host(`freshrss.${CLOUD_DOMAIN}`)
      - traefik.http.routers.freshrss.tls.certresolver=mytlschallenge
      - traefik.http.routers.freshrss.entrypoints=web-secured
      - traefik.http.routers.freshrss.tls=true
      - traefik.http.routers.freshrss.service=freshrss

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5-r0-ls185@sha256:65e4fb3328ba5b402dc98822b7727d0dc266a5e9a827aad3f0e47bf065d4afc1
    container_name: freshrss_mariadb
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=freshrss
      - PUID=1000
      - PGID=1000
    volumes:
      - ../../cloud-data/freshrss/mariadb:/config

networks:
  web:
    external: true
  backend:
    external: false
    internal: false
