- name: SSHD configuration
  hosts: all
  become: true
  tasks:
    - name: Configure SSHD
      ansible.builtin.include_role:
        name: willshersystems.sshd
      vars:
        sshd_install_service: false
        sshd:
          PasswordAuthentication: "no"
          PermitEmptyPasswords: "no"
          PermitRootLogin: "no"
          AllowUsers: cloud

- name: Time
  hosts: all
  become: true
  tasks:
    - name: Install NTP
      ansible.builtin.apt:
        name: ntp
    - name: Start NTP
      ansible.builtin.service:
        name: ntp
        state: started
    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"

- name: USB Drives
  hosts: all
  become: true
  tasks:
    - name: Install pmount
      ansible.builtin.apt:
        name: pmount
