version: '3.7'

services:
  app:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    container_name: fasten
    restart: unless-stopped
    networks:
      - web
    ports: []
    volumes:
      - ../../cloud-data/fasten/db:/opt/fasten/db
      - ../../cloud-data/fasten/cache:/opt/fasten/cache
    labels:
      - traefik.enable=true
      - traefik.http.services.fasten.loadbalancer.server.port=8080

      # HTTPS
      - traefik.http.routers.fasten.rule=Host(`fasten.${CLOUD_DOMAIN}`)
      - traefik.http.routers.fasten.tls.certresolver=mytlschallenge
      - traefik.http.routers.fasten.entrypoints=web-secured
      - traefik.http.routers.fasten.tls=true
      - traefik.http.routers.fasten.service=fasten

      # protect with Authelia
      - traefik.http.routers.fasten.middlewares=authelia@docker

      # Automatically updated
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external: true
